apiVersion: v1
kind: Template
metadata:
  annotations:
    description: |
      Embedded noVNC client and websockify proxy for OpenShift All-In-One demo
    tags: instant-app,util
  name: novnc
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: novnc
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: fedora
  spec:
    dockerImageRepository: library/fedora:22
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: novnc
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: novnc:latest
    source:
      git:
        uri: https://github.com/edseymour/ose-vnc.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: fedora:22
      type: Docker
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: novnc
  spec:
    replicas: 1
    selector:
      deploymentConfig: novnc
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          deploymentConfig: novnc
        name: novnc
      spec:
        containers:
        - env:
          - name: HOSTPORT
            value: openshift.example.com:5900
          image: novnc
          name: novnc
          ports:
          - containerPort: 6080
            protocol: TCP
          resources: {}
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - novnc
        from:
          kind: ImageStream
          name: novnc
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: novnc
  spec:
    ports:
    - name: 6080-tcp
      nodePort: 0
      port: 6080
      protocol: TCP
    selector:
      deploymentConfig: novnc
- apiVersion: v1
  kind: Route
  metadata:
    name: desktop
  spec:
    tls:
      termination: edge
    to:
      kind: Service
      name: novnc
